# Generated by Django 3.0.2 on 2020-02-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
