# Generated by Django 3.0.2 on 2020-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20200202_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
